### ISSUE TITLE
您好，有个问题请教一下

### ISSUE THREAD

**Issue by StudentMrMa** [tuengominh/deap-eeg-classification#1]
for i in files:
    filename = "Pytorch//dataset_DEAP//s1.mat" + i + ".mat"
    trial = read_eeg_signal_from_file(filename)
    labels.append(trial['labels'])
    data.append(trial['data'])
运行这一段代码以后，第三行显示没有相应的字典或文件，找不到相应的文件，可是按照我的这个地址明明存在啊，请问是什么问题呢？

**Comment by tuengominh** [comment]
depends on your OS system, the full path should be sth like:

Windows: "C:\path_to_your_root_folder\PyTorch\..."
Linux: "home\user_name\path_to_your_root_folder\PyTorch\..."
